[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_RUNTIME = "nodejs18.x"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true 